# Data Preparation

## Objectives

- Remove administrative metadata not relevant for analytics
- Convert date columns to datetime format
- Preserve analytical attributes for future reporting and modeling
- Create a cleaned dataset for downstream consumption

## Transformations Applied

### Removed Columns

- habilitado
- rectificado
- idusuario
- observaciones

### Date Conversion

Converted:

- fechaingreso
- fecha_data

to datetime format.

### Output Dataset

The cleaned dataset was exported to:

data/processed/argentina_oil_gas_clean.csv

In [44]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df = pd.read_csv('../data/raw/produccin-de-pozos-de-gas-y-petrleo-2026.csv')

In [45]:
df_clean = df.copy()

In [46]:
df.columns

Index(['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas',
       'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef',
       'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo',
       'observaciones', 'fechaingreso', 'rectificado', 'habilitado',
       'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion',
       'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento',
       'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto',
       'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data'],
      dtype='str')

In [47]:
selected_columns = ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas',
       'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef',
       'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo','fechaingreso',
        'empresa', 'sigla', 'formprod', 'profundidad', 'formacion',
       'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento',
       'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto',
       'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

Omitting the following columns:
* habilitado
* rectificado
* idusuario
* observaciones

In [48]:
df.head()

,idempresa,anio,mes,idpozo,prod_pet,prod_gas,prod_agua,iny_agua,iny_gas,iny_co2,iny_otro,tef,vida_util,tipoextraccion,tipoestado,tipopozo,observaciones,fechaingreso,rectificado,habilitado,idusuario,empresa,sigla,formprod,profundidad,formacion,idareapermisoconcesion,areapermisoconcesion,idareayacimiento,areayacimiento,cuenca,provincia,tipo_de_recurso,proyecto,clasificacion,subclasificacion,sub_tipo_recurso,fecha_data
0,YPF,2026,1,115810,2.46,34.97,0.00,0.0,0.0,0.0,0.0,22.33,NaN,Surgencia Natural,Extracción Efectiva,Gasífero,NaN,2026-02-11 14:43:16.936002,f,t,334,YPF S.A.,YPF.Nq.LLL-259,SBLA,3040.0,sierras blancas,LDL,LOMA LA LATA - SIERRA BARROSA,LDL,LOMA LA LATA,NEUQUINA,Neuquén,CONVENCIONAL,Sin Proyecto,EXPLOTACION,DESARROLLO,NaN,2026-01-31
1,YPF,2026,1,740,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.0,Sin Sistema de Extracción,En Estudio,Petrolífero,Cargado automáticamente como [Sin movimientos],2026-02-13 12:19:36.890403,f,t,334,YPF S.A.,CHE.Md.PPCx-1,FIMP,3757.0,formación improductiva,PPCO,PUESTO POZO CERCADO OCCIDENTAL,PPCO,PUESTO POZO CERCADO OCCIDENTAL,CUYANA,Mendoza,CONVENCIONAL,Sin Proyecto,NaN,NaN,NaN,2026-01-31
2,YPF,2026,1,128473,0.53,0.19,75.93,0.0,0.0,0.0,0.0,30.29,NaN,Cavidad Progresiva,Extracción Efectiva,Petrolífero,NaN,2026-02-11 14:43:16.936002,f,t,334,YPF S.A.,PBE.Nq.PH-1973d,AGRI,1000.0,agrio,PHE,PUESTO HERNANDEZ,HER,PUESTO HERNANDEZ,NEUQUINA,Neuquén,CONVENCIONAL,Sin Proyecto,EXPLOTACION,DESARROLLO,NaN,2026-01-31
3,YPF,2026,1,115812,12.06,253.00,0.00,0.0,0.0,0.0,0.0,18.00,NaN,Surgencia Natural,Extracción Efectiva,Gasífero,NaN,2026-02-11 14:43:16.936002,f,t,334,YPF S.A.,YPF.Nq.LLL-263,SBLA,3115.0,sierras blancas,LDL,LOMA LA LATA - SIERRA BARROSA,LDL,LOMA LA LATA,NEUQUINA,Neuquén,CONVENCIONAL,Sin Proyecto,EXPLOTACION,DESARROLLO,NaN,2026-01-31
4,YPF,2026,1,112655,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,NaN,Sin Sistema de Extracción,Abandonado,Otro tipo,NaN,2026-02-11 14:43:16.936002,f,t,334,YPF S.A.,YPF.RN.SP.a-3,QTUC,1129.0,quintuco,SPR,SEÑAL PICADA - PUNTA BARDA,SPI,SEÑAL PICADA,NEUQUINA,Rio Negro,CONVENCIONAL,Sin Proyecto,EXPLOTACION,AVANZADA,NaN,2026-01-31

In [49]:
df.tail()

,idempresa,anio,mes,idpozo,prod_pet,prod_gas,prod_agua,iny_agua,iny_gas,iny_co2,iny_otro,tef,vida_util,tipoextraccion,tipoestado,tipopozo,observaciones,fechaingreso,rectificado,habilitado,idusuario,empresa,sigla,formprod,profundidad,formacion,idareapermisoconcesion,areapermisoconcesion,idareayacimiento,areayacimiento,cuenca,provincia,tipo_de_recurso,proyecto,clasificacion,subclasificacion,sub_tipo_recurso,fecha_data
328912,2015,2026,4,10222,0.0000,0.00000,0.0000,427.15,0.0,0.0,0.0,30.0,NaN,Sin Sistema de Extracción,En Inyección Efectiva,Inyección de Agua,NaN,2026-05-26 14:00:13.643545,f,t,450,EDHIPSA,AEC.RN.PP-6,LAJA,2786.0,lajas,PUPR,PUESTO PRADO,PPR,PUESTO PRADO,NEUQUINA,Rio Negro,CONVENCIONAL,Sin Proyecto,NaN,NaN,NaN,2026-04-30
328913,2015,2026,4,10224,0.0000,0.00000,0.0000,0.00,0.0,0.0,0.0,0.0,NaN,Bombeo Mecánico,En Estudio,Petrolífero,NaN,2026-05-26 14:00:13.643545,f,t,450,EDHIPSA,AEC.RN.PP-7,LAJA,2854.0,lajas,PUPR,PUESTO PRADO,PPR,PUESTO PRADO,NEUQUINA,Rio Negro,CONVENCIONAL,Sin Proyecto,NaN,NaN,NaN,2026-04-30
328914,2015,2026,4,10255,0.0000,0.00000,0.0000,0.00,0.0,0.0,0.0,0.0,NaN,Sin Sistema de Extracción,Abandono Temporario,Otro tipo,NaN,2026-05-26 14:00:13.643545,f,t,450,EDHIPSA,CSJ.RN.H.x-1,LOMO,2700.0,loma montosa,PUPR,PUESTO PRADO,SIYA,POZOS SIN YACIMIENTO,NEUQUINA,Rio Negro,CONVENCIONAL,Sin Proyecto,EXPLORACION,EXPLORACION,NaN,2026-04-30
328915,2015,2026,4,10223,0.0000,0.00000,0.0000,0.00,0.0,0.0,0.0,0.0,NaN,Sin Sistema de Extracción,En Inyección Efectiva,Inyección de Agua,NaN,2026-05-26 14:00:13.643545,f,t,450,EDHIPSA,AEC.RN.PP-6,PROS,2786.0,punta rosada,PUPR,PUESTO PRADO,PPR,PUESTO PRADO,NEUQUINA,Rio Negro,CONVENCIONAL,Sin Proyecto,NaN,NaN,NaN,2026-04-30
328916,2015,2026,4,10218,10.9193,2.43645,15.1847,0.00,0.0,0.0,0.0,30.0,NaN,Bombeo Mecánico,Extracción Efectiva,Petrolífero,NaN,2026-05-26 14:00:13.643545,f,t,450,EDHIPSA,AEC.RN.PP-3,PREC,2801.0,precuyo,PUPR,PUESTO PRADO,PPR,PUESTO PRADO,NEUQUINA,Rio Negro,CONVENCIONAL,Sin Proyecto,NaN,NaN,NaN,2026-04-30

The dataset already contains a monthly reference date (fecha_data). Therefore, no additional date column was created.

In [50]:
df_clean = df_clean[selected_columns]

In [51]:
print(df.shape)
print(df_clean.shape)

(328917, 38)
(328917, 34)

In [52]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 328917 entries, 0 to 328916
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idempresa               328917 non-null  str
 1   anio                    328917 non-null  int64
 2   mes                     328917 non-null  int64
 3   idpozo                  328917 non-null  int64
 4   prod_pet                328917 non-null  float64
 5   prod_gas                328917 non-null  float64
 6   prod_agua               328917 non-null  float64
 7   iny_agua                328917 non-null  float64
 8   iny_gas                 328917 non-null  float64
 9   iny_co2                 328917 non-null  float64
 10  iny_otro                328917 non-null  float64
 11  tef                     328917 non-null  float64
 12  vida_util               28877 non-null   float64
 13  tipoextraccion          328899 non-null  str
 14  tipoestado              328899 non-null  str
 15  tipopozo                328899 non-null  str
 16  fechaingreso            328917 non-null  str
 17  empresa                 328917 non-null  str
 18  sigla                   328917 non-null  str
 19  formprod                318201 non-null  str
 20  profundidad             328917 non-null  float64
 21  formacion               317775 non-null  str
 22  idareapermisoconcesion  328917 non-null  str
 23  areapermisoconcesion    328917 non-null  str
 24  idareayacimiento        328917 non-null  str
 25  areayacimiento          328917 non-null  str
 26  cuenca                  328905 non-null  str
 27  provincia               328917 non-null  str
 28  tipo_de_recurso         328917 non-null  str
 29  proyecto                328917 non-null  str
 30  clasificacion           263436 non-null  str
 31  subclasificacion        263436 non-null  str
 32  sub_tipo_recurso        19510 non-null   str
 33  fecha_data              328917 non-null  str
dtypes: float64(10), int64(3), str(21)
memory usage: 85.3 MB

In [53]:
df_clean["fechaingreso"] = pd.to_datetime(df_clean["fechaingreso"])
df_clean["fecha_data"] = pd.to_datetime(df_clean["fecha_data"])

In [54]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 328917 entries, 0 to 328916
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idempresa               328917 non-null  str
 1   anio                    328917 non-null  int64
 2   mes                     328917 non-null  int64
 3   idpozo                  328917 non-null  int64
 4   prod_pet                328917 non-null  float64
 5   prod_gas                328917 non-null  float64
 6   prod_agua               328917 non-null  float64
 7   iny_agua                328917 non-null  float64
 8   iny_gas                 328917 non-null  float64
 9   iny_co2                 328917 non-null  float64
 10  iny_otro                328917 non-null  float64
 11  tef                     328917 non-null  float64
 12  vida_util               28877 non-null   float64
 13  tipoextraccion          328899 non-null  str
 14  tipoestado              328899 non-null  str
 15  tipopozo                328899 non-null  str
 16  fechaingreso            328917 non-null  datetime64[us]
 17  empresa                 328917 non-null  str
 18  sigla                   328917 non-null  str
 19  formprod                318201 non-null  str
 20  profundidad             328917 non-null  float64
 21  formacion               317775 non-null  str
 22  idareapermisoconcesion  328917 non-null  str
 23  areapermisoconcesion    328917 non-null  str
 24  idareayacimiento        328917 non-null  str
 25  areayacimiento          328917 non-null  str
 26  cuenca                  328905 non-null  str
 27  provincia               328917 non-null  str
 28  tipo_de_recurso         328917 non-null  str
 29  proyecto                328917 non-null  str
 30  clasificacion           263436 non-null  str
 31  subclasificacion        263436 non-null  str
 32  sub_tipo_recurso        19510 non-null   str
 33  fecha_data              328917 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(10), int64(3), str(19)
memory usage: 85.3 MB

## Null values

In [55]:
df_clean.isnull().sum().sort_values(ascending=False)

sub_tipo_recurso          309407
vida_util                 300040
clasificacion              65481
subclasificacion           65481
formacion                  11142
formprod                   10716
tipopozo                      18
tipoestado                    18
tipoextraccion                18
cuenca                        12
anio                           0
idempresa                      0
iny_co2                        0
iny_gas                        0
mes                            0
idpozo                         0
prod_pet                       0
prod_gas                       0
empresa                        0
fechaingreso                   0
tef                            0
iny_otro                       0
prod_agua                      0
iny_agua                       0
sigla                          0
profundidad                    0
areayacimiento                 0
idareayacimiento               0
areapermisoconcesion           0
idareapermisoconcesion         0
proyecto                       0
tipo_de_recurso                0
provincia                      0
fecha_data                     0
dtype: int64

## Duplicated values

In [56]:
df_clean.duplicated(subset=["idpozo", "anio", "mes"]).sum()

np.int64(0)

## Cleaned dataset saving

In [57]:
df_clean.to_csv("../data/processed/argentina_oil_gas_clean.csv",index=False)